### PR TITLE
Allow using Twig 3

### PR DESCRIPTION
**Pull request by javiereguiluz**

### CODE REVIEW

**Review by nikophil — COMMENTED** [review]
be careful, we have a twig deprecation when php tests run:
```
1x: The spaceless tag in "paragraph.html.twig" at line 1 is deprecated since Twig 2.7, use the "spaceless" filter with the "apply" tag instead.
```

**Review by nikophil — COMMENTED** [review]
sorry @javiereguiluz actually *our* spaceless were good: `{% apply spaceless %}`
the deprecation is coming from `doctrine/rst-parser` which uses `{% spaceless %}`

but then doesn't this mean `doctrine/rst-parser` is not compatible with twig3, and then we are not?

**Comment by javiereguiluz** [comment]
@nikophil I've reverted changes.

I don't know if it's possible ... but doctrine/rst-parser should release a stable version and merge the pending PRs ... and this project should update dependencies too. The doctrine/rst-parser + docs-builder + symfony.com dependency updating is badly broken at the moment. We need stability to work on improving things. Thanks! 🙏

**Review by nikophil — APPROVED** [review]
ok, i see :D
https://github.com/doctrine/rst-parser/pull/130

**Pull request merged**
